package com.mbg.mapper;

import com.mbg.entity.Cat;
import com.mbg.entity.CatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Thu Aug 12 07:45:08 CST 2021
     */
    long countByExample(CatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Thu Aug 12 07:45:08 CST 2021
     */
    int deleteByExample(CatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Thu Aug 12 07:45:08 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Thu Aug 12 07:45:08 CST 2021
     */
    int insert(Cat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Thu Aug 12 07:45:08 CST 2021
     */
    int insertSelective(Cat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Thu Aug 12 07:45:08 CST 2021
     */
    List<Cat> selectByExample(CatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Thu Aug 12 07:45:08 CST 2021
     */
    Cat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Thu Aug 12 07:45:08 CST 2021
     */
    int updateByExampleSelective(@Param("record") Cat record, @Param("example") CatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Thu Aug 12 07:45:08 CST 2021
     */
    int updateByExample(@Param("record") Cat record, @Param("example") CatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Thu Aug 12 07:45:08 CST 2021
     */
    int updateByPrimaryKeySelective(Cat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbg.generated Thu Aug 12 07:45:08 CST 2021
     */
    int updateByPrimaryKey(Cat record);
}